version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: etat_civil_postgres
    restart: always
    environment:
      POSTGRES_DB: etat_civil
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: